### ISSUE TITLE
Dear kukdh1

### ISSUE THREAD

**Issue by yuma00** [kukdh1/AokanaCGExtractor#1]
Dear kukdh1,
My English is not good, sorry......

You write a program, "AokanaCGExtractor"
I download use "Microsoft Visual Studio Ultimate 2013" open, there will be many errors.

These errors may be set in my relationship with the environment.

"AokanaCGExtractor.exe files" you can provide it?

THX!

**Comment by kukdh1** [comment]
I added executable file in /Release directory.
Please check.

**Comment by yuma00** [comment]
Dear kukdh1,

Thanks for your palindrome.
My English is not good, sorry......

You provide "exe file", "start button" after pressing,
Addition to the button name becomes "stop", no other reaction.

My OS is win7, the Japanese language.
'Aono Kanatano Four Rhythm(蒼の彼方のフォーリズム)' has to use to crack the program.
Will these factors will be affected?

This is a video my executed。
http://youtu.be/X49jAEND5Vk


Thank you!
