### ISSUE TITLE
Dear kukdh1,

### ISSUE THREAD

**Issue by yuma00** [kukdh1/AokanaCGExtractor#2]
Dear kukdh1,

Thanks for your palindrome.
My English is not good, sorry......

You provide "exe file", "start button" after pressing,
Addition to the button name becomes "stop", no other reaction.

My OS is win7, the Japanese language.
'Aono Kanatano Four Rhythm(蒼の彼方のフォーリズム)' has to use to crack the program.
Will these factors will be affected?

This is a video my executed。
http://youtu.be/X49jAEND5Vk

Thank you!

**Comment by kukdh1** [comment]
This program hooks memory when BGI interpreter reads encrypted CG file.
In your video, you pressed start button 'after' the CG file was loaded. you should press start button 'before' the CG file being load.
It may works when you press start button before the CG menu.

このプラグラムはBGIインタプリタが暗号化されたCGファイルをロードして復号化した後にメモリを読んで復号化されたCGファイルを保存するプログラムです。
あなたの映像では既にCGファイルがロードされたあとにスタートボタンを押したので何も表示されません。
ゲームのメイン画面でスタートボタンを押してCGメニューに入ったらCGのThumbnailイメージがリストに表示されるはずです。

**Comment by yuma00** [comment]
Dear kukdh1,

Thank for your palindrome again.

After several attempts,  now able to perform properly the program.
When the game starts, "start button" is pressed
These pictures can be read correctly

Thanks for your help again.

-------------------------------------------------------------------
kukdh1さんこんにちは

ボクの日本語も下手です、どもよろしくお願いします。

返信ありがとうございました。
いくつかの試みの後、今プログラムを正常に実行する。
ゲームが起動する時スタートボタンを押さえつけます
画像に読み込むことができる。

再びあなたの助けをありがとう＾＾
